### ISSUE TITLE
Mostly everthing is great but

### ISSUE THREAD

**Issue by AlexandruCardas** [guettli/programming-guidelines#7]
I agree with you on most topics but in terms of learning python could you elaborate a bit more as to why we should study lower level languages such as C?

Also I have found numerous articles and blog post from people that swear by learning vim or emacs instead of a modern IDE which simplifies and almost dumbs down the role of a programmer and over relying on technology for learning aspects of a language.

Would gladly discuss these thoughts because I am trying to understand people's perspective and know what is the appropriate path for a fully learning roadmap.

Design patterns are indeed overrated, I haven't seen a by the book implementation of a design pattern so far, only bastardizations with a prefix attached to them. How can students learn from these and where should we draw the line?

Any tips on to how I can encourage people to bring their own life into programming? Sports, memories, life and passions? Most people I see code like robots and their code is genuinely boring without any imagination or creativity. I can see flavorful code into someone who is passionate about coding and their own past times.

**Comment by guettli** [comment]
I am unsure, maybe it is not needed to learn C. If you have done some C programming with malloc() and free(), then you will love languages with garbage collection. But on the other hand, if you know Python, I think you would learn more by learning for example terraform instead of C.

Concerning IDE: I use the IDE for coding. This means typing code, and navigating in the code. But I do commit and push the code on the command line.

The find/grep/pipe fun on the linux command line is still handy, but it gets less important every day.

you say fully learning roadmap ... You could have a look at the part I added today. See: https://github.com/guettli/programming-guidelines/blob/master/README.md#false-means-failure-the-root-cause-is-gone

Now imagine there are 19 implementations of this method and 40 calls to this method.

Now imagine you want to update the API from "return false" to "raise Exception".

This takes long. Refactoring and dealing with legacy code is one part of the roadmap. I guess there are not many
tutorials about this. What can you do if code which is not in your area of influence uses the old way of a method...
and you want to refactor it. Technical debt can slow you down a lot.

Thank you for your feedback concerning design patterns.

Why do you want to encourage people to bring their own life into programming? If I understood your goal, then I might find a answer.

What is the problem with boring code? I like boring code, since I think "obvious" is a synonym to "boring". And things should
be obvious.

**Comment by guettli** [comment]
Hi @AlexandruCardas this is the manual time-out bot. Please speak up :-)

**Comment by AlexandruCardas** [comment]
In regards to the life into programming, I meant bringing aptitudes that we learn from our day to day rather than becoming a robot while programming.

Yes boring/obvious code is good I guess you are right. I can see however how people's habits can be be brought into code. So for example being messy and unorganized will have an effect on your coding style. If you are more disciplined that can be seen in the simplicity and detail of code.

**Comment by guettli** [comment]
Yes, simplicity is the goal.
